### ISSUE TITLE
Treeview 'heading_configure' method not working.

### ISSUE THREAD

**Issue by vin1antme** [AndyObtiva/glimmer-dsl-tk#6]
When trying to setup column headings text of treeview control using the code below, 'heading_configure' method call fails with error
"ERROR: `headingconfigure': wrong number of arguments (given 0, expected 2..3) (ArgumentError)":
```
require "glimmer-dsl-tk"

include Glimmer

root {
    treeview {
        columns %w(country capital currency)
        show :headings 
        heading_configure "country", :text => 'Country'
        heading_configure "capital", :text => 'Capital'
        heading_configure "currency", :text => 'Currency'
    }
}.open
```
Glimmer-dsl-tk   version 0.0.10 was used.

**Comment by AndyObtiva** [comment]
Handled with very minimal work in version [0.0.11](https://rubygems.org/gems/glimmer-dsl-tk/versions/0.0.11)!

You now see the attached screenshot when running the code:
![Screen Shot 2021-09-28 at 8 43 28 PM](https://user-images.githubusercontent.com/23052/135184756-33c92d2c-ed91-4f3b-b84f-e54f7e8a4aeb.png)

Ideally, I would support data-binding for [treeview](https://tkdocs.com/tutorial/tree.html) just like I do in Glimmer DSL for SWT as demonstrated by the [Hello, Tree! sample](https://github.com/AndyObtiva/glimmer-dsl-swt/blob/master/docs/reference/GLIMMER_SAMPLES.md#hello-tree), but unfortunately I am too busy right now with [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui), which is a more complete alternative to [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) that you might find interesting (albeit based on a [less mature toolkit](https://github.com/andlabs/libui) with less features).

If I do find bandwidth to get more work done on [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) in the future, you will know if you [watch](https://github.com/AndyObtiva/glimmer-dsl-tk/watchers) the project on GitHub.

In any case, keep the feedback coming. It only helps!

Cheers!
